update: linux-gnu/Makefile test target

diff --git a/build/platforms/linux-gnu/btest/usr/local/bin/btest b/build/platforms/linux-gnu/btest/usr/local/bin/btest
--- a/build/platforms/linux-gnu/btest/usr/local/bin/btest
+++ b/build/platforms/linux-gnu/btest/usr/local/bin/btest
@@ -1,16 +1,17 @@
 #!/bin/bash
 
 # btest - Bash Testing Framework
-# Version: 0.3.0
 # Author: Murat Ünalan <murat.uenalan@gmail.com>
 
 set -e
 
-BT_HARNESS_VERSION=0.01
+#set -x  # Enable trace debugging
 
-if [[ ! "$BT_DIR" ]]; then
+BT_HARNESS_VERSION=0.02
 
-    export BT_DIR=/usr/local/lib/btest/
+if [[ ! "$BT_OPT_DIR" ]]; then
+
+    export BT_OPT_DIR=/usr/local/lib/btest/
 
 fi
 
@@ -33,11 +34,12 @@ fi
 
 # Source the btest library
 
-source $BT_DIR/btest.bash
+source $BT_OPT_DIR/btest.bash
 
+trap '' EXIT   # overwrite the automatic trap from btest.bash
 
 # Function to display help
-display_help() {
+function display_help() {
     cat << EOF
 Usage: btest <command> [options]
 
@@ -54,43 +56,50 @@ Global Options:
   -v, --version   Display the version of btest
   -h, --help      Display this help message
 EOF
+
+    return 0
 }
 
 # Function to display version
-display_version() {
+function display_version() {
 
     echo "BT_VERSION=$BT_VERSION"
 
+    return 0
 }
 
 # Subcommand functions
 
 # Function to parse options
-parse_options() {
+function parse_options() {
     while [[ $# -gt 0 ]]; do
 	case $1 in
 	    -r|--reporter)
-		REPORTER=${2:-$BTEST_REPORTER}
+		BT_OPT_REPORTER=${2:-$BT_OPT_REPORTER_DEFAULT}
 		shift 2
 		;;
 	    -o|--output)
-		OUTPUT_FILE=${2:-$BTEST_OUTPUT_FILE}
+		BT_OPT_OUTPUT_FILE=${2:-$BT_OPT_OUTPUT_FILE_DEFAULT}
+		shift 2
+		;;
+	    -l|--loglevel)
+		BT_OPT_LOG_LEVEL=${2:-$BT_OPT_LOG_LEVEL_DEFAULT}
 		shift 2
 		;;
 	    -v|--verbose)
-		VERBOSE=${BTEST_VERBOSE:-1}
+		BT_OPT_VERBOSE=${BT_OPT_VERBOSE_DEFAULT:-1}
 		shift
-		;;
-	    -l|--loglevel)
-		LOG_LEVEL=${2:-$BTEST_LOG_LEVEL}
-		shift 2
 		;;
 	    -p|--parallel)
-		PARALLEL=${BTEST_PARALLEL:-1}
+		BT_OPT_PARALLEL=${BT_OPT_PARALLEL_DEFAULT:-0}
 		shift
 		;;
+	    -t|--tree)
+		BT_OPT_FLAG_TREE=${BT_OPT_FLAG_TREE_DEFAULT:-0}
+		shift 
+		;;
 	    -d|--dry-run)
-		DRY_RUN=${BTEST_DRY_RUN:-1}
+		BT_OPT_FLAG_DRY_RUN=${BT_OPT_FLAG_DRY_RUN_DEFAULT:-0}
 		shift
 		;;
 	    -h|--help)
@@ -105,13 +114,13 @@ parse_options() {
     return 0
 }
 
-cmd_version() {
+function cmd_version() {
 
     display_version
 
 }
 
-cmd_file() {
+function cmd_file() {
     local OPTIND
     OPTIND=1
     
@@ -128,21 +137,44 @@ cmd_file() {
         return 1
     fi
 
-    [ "$VERBOSE" = "1" ] && echo "Verbose mode enabled"
-    [ "$LOG_LEVEL" ] && echo "Log level set to $LOG_LEVEL"
-    [ "$DRY_RUN" = "1" ] && echo "Dry run mode enabled"
+    [ "$BT_OPT_VERBOSE" = "1" ] && bt_echo "OPT: Verbose mode enabled"
+    [ "$BT_OPT_LOG_LEVEL" ] && bt_echo "OPT: Log level set to $BT_OPT_LOG_LEVEL"
+    [ "$BT_OPT_FLAG_DRY_RUN" = "1" ] && bt_echo "OPT: Dry run mode enabled"
 
+
+    if [[ "$BT_OPT_FLAG_MARKDOWN_MODE" -gt 0 ]]; then
+        
+        echo "# TEST HARNESS INFO"
+
+        echo "The test harness 'btest' has been used. Following further information:"
+
+        echo " - BT_VERSION=$BT_VERSION"
+
+    fi
+    
     for file in "$@"; do
         if [ ! -f "$file" ]; then
             echo "Error: File not found: $file" >&2
             continue
         fi
-        echo "Running tests in file: $file"
-        [ "$DRY_RUN" != "1" ] && bash "$file"
+
+        bt_echo "Running tests in file: $file"
+
+        BT_INFO_FILE=$file
+        
+        if [[ "$BT_OPT_FLAG_DRY_RUN" != "1" ]]; then
+
+            bash "$file"
+
+            echo "'btest file $file' sub-bash return value $?"
+        fi
+        
     done
+
+    return 0
 }
 
-cmd_folder() {
+function cmd_folder() {
 
     local OPTIND
     OPTIND=1
@@ -160,37 +192,61 @@ cmd_folder() {
         return 1
     fi
 
-    [ "$VERBOSE" = "1" ] && echo "Verbose mode enabled"
-    [ "$LOG_LEVEL" ] && echo "Log level set to $LOG_LEVEL"
-    [ "$PARALLEL" = "1" ] && echo "Parallel execution enabled"
-    [ "$DRY_RUN" = "1" ] && echo "Dry run mode enabled"
+    [ "$BT_OPT_VERBOSE" = "1" ] && bt_echo "OPT: Verbose mode enabled"
+    [ "$BT_OPT_LOG_LEVEL" ] && bt_echo "OPT: Log level set to $BT_OPT_LOG_LEVEL"
+    [ "$BT_OPT_FLAG_PARALLEL" = "1" ] && bt_echo "OPT: Parallel execution enabled"
+    [ "$BT_OPT_FLAG_DRY_RUN" = "1" ] && bt_echo "OPT: Dry run mode enabled"
+    [ "$BT_OPT_FLAG_TREE" = "1" ] && bt_echo "OPT: Tree enabled"
 
     for folder in "$@"; do
         if [ ! -d "$folder" ]; then
             echo "Error: Folder not found: $folder" >&2
             continue
         fi
-        echo "Running tests in folder: $folder"
+
+        echo "FOLDER: $folder "
+
+        BT_INFO_FOLDER=$folder
+
         if [ "$PARALLEL" = "1" ]; then
-            find "$folder" -name "*.bash" -type f | xargs -P0 -I{} bash {}
+            find "$folder" -name "*_test.bash" -type f | xargs -P0 -I{} bash {}
         else
-            for file in "$folder"/*.bash; do
+
+            if [[ "$BT_OPT_FLAG_TREE" -gt 0 ]]; then
+                
+            for file in $(find "$folder" -name "*_test.bash" -type f); do
                 if [ -f "$file" ]; then
-                    echo "Running test file: $file"
-                    [ "$DRY_RUN" != "1" ] && bash "$file"
+                    echo "  FILE: $file"
+
+                    [ "$BT_OPT_FLAG_DRY_RUN" != "1" ] && BT_INFO_FOLDER="$BT_INFO_FOLDER" BT_INFO_FILE="$file" bash "$file"
                 fi
             done
+
+            else
+
+                for file in $(find "$folder" -maxdepth 1 -name "*_test.bash" -type f); do
+                    if [ -f "$file" ]; then
+                        bt_echo "  FILE: Test file: $file"
+
+                        [ "$BT_OPT_FLAG_DRY_RUN" != "1" ] && BT_INFO_FOLDER="$BT_INFO_FOLDER" BT_INFO_FILE=$file bash "$file"
+                    fi
+                done
+
+            fi
+            
         fi
     done
+
+    return 0
 }
 
-cmd_generate() {
+function cmd_generate() {
     local OPTIND
     OPTIND=1
 
     while getopts ":o:h" opt; do
         case $opt in
-            o) OUTPUT_DIR=${OPTARG:-$BTEST_OUTPUT_DIR} ;;
+            o) BT_OPT_OUTPUT_DIR=${OPTARG:-$BT_OPT_OUTPUT_DIR_DEFAULT} ;;
             h) cmd_help generate; return ;;
             :) echo "Option -$OPTARG requires an argument." >&2; return 1 ;;
             \?) echo "Invalid option: -$OPTARG" >&2; return 1 ;;
@@ -205,13 +261,13 @@ cmd_generate() {
     fi
 
     test_name=$1
-    output_dir=${OUTPUT_DIR:-$PWD}
+    output_dir=${BT_OPT_OUTPUT_DIR:-$PWD}
     output_file="$output_dir/${test_name}_test.bash"
 
     cat > "$output_file" << EOF
 #!/bin/bash
 
-source \$BT_DIR/btest.bash
+source \$BT_OPT_DIR/btest.bash
 
 bt_begin "$test_name" 1
 
@@ -225,22 +281,22 @@ EOF
     echo "Generated test file: $output_file"
 }
 
-cmd_status() {
+function cmd_status() {
     local OPTIND
     OPTIND=1
 
     while getopts ":vl:" opt; do
         case $opt in
-            v) VERBOSE=${BTEST_VERBOSE:-1} ;;
-            l) LOG_LEVEL=${OPTARG:-$BTEST_LOG_LEVEL} ;;
+            v) OPT_VERBOSE=${BT_OPT_VERBOSE:-1} ;;
+            l) LOG_LEVEL=${OPTARG:-$BT_OPT_LOG_LEVEL} ;;
             :) echo "Option -$OPTARG requires an argument." >&2; return 1 ;;
             \?) echo "Invalid option: -$OPTARG" >&2; return 1 ;;
         esac
     done
     shift $((OPTIND-1))
 
-    [ "$VERBOSE" = "1" ] && echo "Verbose mode enabled"
-    [ "$LOG_LEVEL" ] && echo "Log level set to $LOG_LEVEL"
+    [ "$BT_OPT_VERBOSE" = "1" ] && bt_echo "OPT: Verbose mode enabled"
+    [ "$BT_OPT_LOG_LEVEL" ] && bt_echo "OPT: Log level set to $BT_OPT_LOG_LEVEL"
 
     if ! command -v tree &> /dev/null; then
         echo "Error: 'tree' command not found. Please install it to use the status command." >&2
@@ -249,9 +305,11 @@ cmd_status() {
 
     echo "Available tests:"
     tree -P "*_test.bash" --prune
+
+    return 0
 }
 
-cmd_help() {
+function cmd_help() {
     case $1 in
         file)
             cat << EOF
@@ -267,11 +325,12 @@ Options:
   -d, --dry-run   Perform a dry run without executing tests
 
 Environment variables:
-  BTEST_REPORTER      Set the default reporter
-  BTEST_OUTPUT_FILE   Set the default output file
-  BTEST_VERBOSE       Set verbose mode (0 or 1)
-  BTEST_LOG_LEVEL     Set the default log level
-  BTEST_DRY_RUN       Set dry run mode (0 or 1)
+  BT_REPORTER      Set the default reporter
+  BT_OUTPUT_FILE   Set the default output file
+  BT_OPT_VERBOSE       Set verbose mode (0 or 1)
+  BT_OPT_LOG_LEVEL     Set the default log level
+  BT_OPT_FLAG_DRY_RUN       Set dry run mode (0 or 1)
+  BT_OPT_FLAG_MARKDOWN_MODE Toggle extra markdown output
 EOF
             ;;
         folder)
@@ -287,14 +346,17 @@ Options:
   -l, --loglevel  Set the log level
   -p, --parallel  Run tests in parallel
   -d, --dry-run   Perform a dry run without executing tests
+  -t              Tree of tests (descend into all subfolders)
 
 Environment variables:
-  BTEST_REPORTER      Set the default reporter
-  BTEST_OUTPUT_FILE   Set the default output file
-  BTEST_VERBOSE       Set verbose mode (0 or 1)
-  BTEST_LOG_LEVEL     Set the default log level
-  BTEST_PARALLEL      Set parallel execution mode (0 or 1)
-  BTEST_DRY_RUN       Set dry run mode (0 or 1)
+  BT_REPORTER      Set the default reporter
+  BT_OUTPUT_FILE   Set the default output file
+  BT_OPT_VERBOSE       Set verbose mode (0 or 1)
+  BT_OPT_LOG_LEVEL     Set the default log level
+  BT_OPT_PARALLEL      Set parallel execution mode (0 or 1)
+  BT_OPT_FLAG_DRY_RUN       Set dry run mode (0 or 1)
+  BT_OPT_FLAG_TREE Set the default subfolder behavior
+  BT_OPT_FLAG_MARKDOWN_MODE Toggle extra markdown output
 EOF
             ;;
         generate)
@@ -307,7 +369,7 @@ Options:
   -o <directory>  Specify the output directory (default: current directory)
 
 Environment variables:
-  BTEST_OUTPUT_DIR    Set the default output directory
+  BT_OPT_OUTPUT_DIR_DEFAULT    Set the default output directory
 EOF
             ;;
         status)
@@ -321,17 +383,29 @@ Options:
   -l, --loglevel  Set the log level
 
 Environment variables:
-  BTEST_VERBOSE       Set verbose mode (0 or 1)
-  BTEST_LOG_LEVEL     Set the default log level
+  BT_OPT_VERBOSE       Set verbose mode (0 or 1)
+  BT_OPT_LOG_LEVEL     Set the default log level
 EOF
             ;;
         *)
             display_help
             ;;
     esac
+
+    return 0
 }
 
+
+
+
+
 # Main command processing
+
+BT_DECLARE_PRE="      " bt_init VERBOSE REPORTER OUTPUT_DIR EPOCH_DELTA_MIN ABORT DIR_DEFAULT DEBUG LOG_LEVEL FLAG_DRY_RUN FLAG_TREE FLAG_MARKDOWN_MODE
+
+BT_DECLARE_PRE="export" bt_init EPOCH_DELTA_MIN PROTOCOL
+
+
 case $1 in
     version)
         shift
@@ -364,8 +438,15 @@ case $1 in
         display_help
         ;;
     *)
-        echo "Error: Unknown command '$1'" >&2
+        if [[ "$2" ]]; then
+
+            echo "Error: Unknown btest subcommand '$1'" >&2
+
+        fi
+
         display_help
+
         exit 1
         ;;
 esac
+
