- major revision: renaming all local and global variables. - New functions to init global/local variables.

diff --git a/template/bin/btest b/template/bin/btest
--- a/template/bin/btest
+++ b/template/bin/btest
@@ -8,9 +8,9 @@ set -e
 
 BT_HARNESS_VERSION=0.02
 
-if [[ ! "$BT_DIR" ]]; then
+if [[ ! "$BT_OPT_DIR" ]]; then
 
-    export BT_DIR=/usr/local/lib/btest/
+    export BT_OPT_DIR=/usr/local/lib/btest/
 
 fi
 
@@ -33,11 +33,11 @@ fi
 
 # Source the btest library
 
-source $BT_DIR/btest.bash
+source $BT_OPT_DIR/btest.bash
 
 
 # Function to display help
-display_help() {
+function display_help() {
     cat << EOF
 Usage: btest <command> [options]
 
@@ -57,7 +57,7 @@ EOF
 }
 
 # Function to display version
-display_version() {
+function display_version() {
 
     echo "BT_VERSION=$BT_VERSION"
 
@@ -66,35 +66,35 @@ display_version() {
 # Subcommand functions
 
 # Function to parse options
-parse_options() {
+function parse_options() {
     while [[ $# -gt 0 ]]; do
 	case $1 in
-	    -t|--tree)
-		OPT_FLAG_TREE=${2:-$BTEST_OPT_FLAG_TREE}
-		shift 2
-		;;
 	    -r|--reporter)
-		REPORTER=${2:-$BTEST_REPORTER}
+		BT_OPT_REPORTER=${2:-$BT_OPT_REPORTER_DEFAULT}
 		shift 2
 		;;
 	    -o|--output)
-		OUTPUT_FILE=${2:-$BTEST_OUTPUT_FILE}
+		BT_OPT_OUTPUT_FILE=${2:-$BT_OPT_OUTPUT_FILE_DEFAULT}
+		shift 2
+		;;
+	    -l|--loglevel)
+		BT_OPT_LOG_LEVEL=${2:-$BT_OPT_LOG_LEVEL_DEFAULT}
 		shift 2
 		;;
 	    -v|--verbose)
-		VERBOSE=${BTEST_VERBOSE:-1}
+		BT_OPT_VERBOSE=${BT_OPT_VERBOSE_DEFAULT:-1}
 		shift
-		;;
-	    -l|--loglevel)
-		LOG_LEVEL=${2:-$BTEST_LOG_LEVEL}
-		shift 2
 		;;
 	    -p|--parallel)
-		PARALLEL=${BTEST_PARALLEL:-1}
+		BT_OPT_PARALLEL=${BT_OPT_PARALLEL_DEFAULT:-0}
 		shift
 		;;
+	    -t|--tree)
+		BT_OPT_FLAG_TREE=${BT_OPT_FLAG_TREE_DEFAULT:-0}
+		shift 
+		;;
 	    -d|--dry-run)
-		DRY_RUN=${BTEST_DRY_RUN:-1}
+		BT_OPT_FLAG_DRY_RUN=${BT_OPT_FLAG_DRY_RUN_DEFAULT:-0}
 		shift
 		;;
 	    -h|--help)
@@ -109,13 +109,13 @@ parse_options() {
     return 0
 }
 
-cmd_version() {
+function cmd_version() {
 
     display_version
 
 }
 
-cmd_file() {
+function cmd_file() {
     local OPTIND
     OPTIND=1
     
@@ -132,9 +132,9 @@ cmd_file() {
         return 1
     fi
 
-    [ "$VERBOSE" = "1" ] && echo "Verbose mode enabled"
-    [ "$LOG_LEVEL" ] && echo "Log level set to $LOG_LEVEL"
-    [ "$DRY_RUN" = "1" ] && echo "Dry run mode enabled"
+    [ "$BT_OPT_VERBOSE" = "1" ] && bt_echo "OPT: Verbose mode enabled"
+    [ "$BT_OPT_LOG_LEVEL" ] && bt_echo "OPT: Log level set to $BT_OPT_LOG_LEVEL"
+    [ "$BT_OPT_FLAG_DRY_RUN" = "1" ] && bt_echo "OPT: Dry run mode enabled"
 
     for file in "$@"; do
         if [ ! -f "$file" ]; then
@@ -142,11 +142,11 @@ cmd_file() {
             continue
         fi
         echo "Running tests in file: $file"
-        [ "$DRY_RUN" != "1" ] && bash "$file"
+        [ "$BT_OPT_FLAG_DRY_RUN" != "1" ] && bash "$file"
     done
 }
 
-cmd_folder() {
+function cmd_folder() {
 
     local OPTIND
     OPTIND=1
@@ -164,11 +164,11 @@ cmd_folder() {
         return 1
     fi
 
-    [ "$VERBOSE" = "1" ] && echo "Verbose mode enabled"
-    [ "$LOG_LEVEL" ] && echo "Log level set to $LOG_LEVEL"
-    [ "$PARALLEL" = "1" ] && echo "Parallel execution enabled"
-    [ "$DRY_RUN" = "1" ] && echo "Dry run mode enabled"
-    [ "$OPT_FLAG_TREE" = "1" ] && echo "Tree enabled"
+    [ "$BT_OPT_VERBOSE" = "1" ] && bt_echo "OPT: Verbose mode enabled"
+    [ "$BT_OPT_LOG_LEVEL" ] && bt_echo "OPT: Log level set to $BT_OPT_LOG_LEVEL"
+    [ "$BT_OPT_FLAG_PARALLEL" = "1" ] && bt_echo "OPT: Parallel execution enabled"
+    [ "$BT_OPT_FLAG_DRY_RUN" = "1" ] && bt_echo "OPT: Dry run mode enabled"
+    [ "$BT_OPT_FLAG_TREE" = "1" ] && bt_echo "OPT: Tree enabled"
 
     for folder in "$@"; do
         if [ ! -d "$folder" ]; then
@@ -176,7 +176,7 @@ cmd_folder() {
             continue
         fi
 
-        echo "# Test results in folder: $folder "
+        echo "FOLDER: Test results in folder: $folder "
 
         if [ "$PARALLEL" = "1" ]; then
             find "$folder" -name "*_test.bash" -type f | xargs -P0 -I{} bash {}
@@ -186,8 +186,8 @@ cmd_folder() {
                 
             for file in $(find "$folder" -name "*_test.bash" -type f); do
                 if [ -f "$file" ]; then
-                    echo "## Test file: $file"
-                    [ "$DRY_RUN" != "1" ] && bash "$file"
+                    echo "  FILE: Test file: $file"
+                    [ "$BT_OPT_FLAG_DRY_RUN" != "1" ] && bash "$file"
                 fi
             done
 
@@ -195,8 +195,8 @@ cmd_folder() {
 
                 for file in $(find "$folder" -maxdepth 1 -name "*_test.bash" -type f); do
                     if [ -f "$file" ]; then
-                        echo "## Test file: $file"
-                        [ "$DRY_RUN" != "1" ] && bash "$file"
+                        echo "  FILE: Test file: $file"
+                        [ "$BT_OPT_FLAG_DRY_RUN" != "1" ] && bash "$file"
                     fi
                 done
 
@@ -206,13 +206,13 @@ cmd_folder() {
     done
 }
 
-cmd_generate() {
+function cmd_generate() {
     local OPTIND
     OPTIND=1
 
     while getopts ":o:h" opt; do
         case $opt in
-            o) OUTPUT_DIR=${OPTARG:-$BTEST_OUTPUT_DIR} ;;
+            o) BT_OPT_OUTPUT_DIR=${OPTARG:-$BT_OPT_OUTPUT_DIR_DEFAULT} ;;
             h) cmd_help generate; return ;;
             :) echo "Option -$OPTARG requires an argument." >&2; return 1 ;;
             \?) echo "Invalid option: -$OPTARG" >&2; return 1 ;;
@@ -227,13 +227,13 @@ cmd_generate() {
     fi
 
     test_name=$1
-    output_dir=${OUTPUT_DIR:-$PWD}
+    output_dir=${BT_OPT_OUTPUT_DIR:-$PWD}
     output_file="$output_dir/${test_name}_test.bash"
 
     cat > "$output_file" << EOF
 #!/bin/bash
 
-source \$BT_DIR/btest.bash
+source \$BT_OPT_DIR/btest.bash
 
 bt_begin "$test_name" 1
 
@@ -247,22 +247,22 @@ EOF
     echo "Generated test file: $output_file"
 }
 
-cmd_status() {
+function cmd_status() {
     local OPTIND
     OPTIND=1
 
     while getopts ":vl:" opt; do
         case $opt in
-            v) VERBOSE=${BTEST_VERBOSE:-1} ;;
-            l) LOG_LEVEL=${OPTARG:-$BTEST_LOG_LEVEL} ;;
+            v) OPT_VERBOSE=${BT_OPT_VERBOSE:-1} ;;
+            l) LOG_LEVEL=${OPTARG:-$BT_OPT_LOG_LEVEL} ;;
             :) echo "Option -$OPTARG requires an argument." >&2; return 1 ;;
             \?) echo "Invalid option: -$OPTARG" >&2; return 1 ;;
         esac
     done
     shift $((OPTIND-1))
 
-    [ "$VERBOSE" = "1" ] && echo "Verbose mode enabled"
-    [ "$LOG_LEVEL" ] && echo "Log level set to $LOG_LEVEL"
+    [ "$BT_OPT_VERBOSE" = "1" ] && bt_echo "OPT: Verbose mode enabled"
+    [ "$BT_OPT_LOG_LEVEL" ] && bt_echo "OPT: Log level set to $BT_OPT_LOG_LEVEL"
 
     if ! command -v tree &> /dev/null; then
         echo "Error: 'tree' command not found. Please install it to use the status command." >&2
@@ -273,7 +273,7 @@ cmd_status() {
     tree -P "*_test.bash" --prune
 }
 
-cmd_help() {
+function cmd_help() {
     case $1 in
         file)
             cat << EOF
@@ -289,12 +289,11 @@ Options:
   -d, --dry-run   Perform a dry run without executing tests
 
 Environment variables:
-  BTEST_REPORTER      Set the default reporter
-  BTEST_REPORTER      Set the default reporter
-  BTEST_OUTPUT_FILE   Set the default output file
-  BTEST_VERBOSE       Set verbose mode (0 or 1)
-  BTEST_LOG_LEVEL     Set the default log level
-  BTEST_DRY_RUN       Set dry run mode (0 or 1)
+  BT_REPORTER      Set the default reporter
+  BT_OUTPUT_FILE   Set the default output file
+  BT_OPT_VERBOSE       Set verbose mode (0 or 1)
+  BT_OPT_LOG_LEVEL     Set the default log level
+  BT_OPT_FLAG_DRY_RUN       Set dry run mode (0 or 1)
 EOF
             ;;
         folder)
@@ -313,13 +312,13 @@ Options:
   -t              Tree of tests (descend into all subfolders)
 
 Environment variables:
-  BTEST_REPORTER      Set the default reporter
-  BTEST_OUTPUT_FILE   Set the default output file
-  BTEST_VERBOSE       Set verbose mode (0 or 1)
-  BTEST_LOG_LEVEL     Set the default log level
-  BTEST_PARALLEL      Set parallel execution mode (0 or 1)
-  BTEST_DRY_RUN       Set dry run mode (0 or 1)
-  BTEST_OPT_FLAG_TREE Set the default subfolder behavior
+  BT_REPORTER      Set the default reporter
+  BT_OUTPUT_FILE   Set the default output file
+  BT_OPT_VERBOSE       Set verbose mode (0 or 1)
+  BT_OPT_LOG_LEVEL     Set the default log level
+  BT_OPT_PARALLEL      Set parallel execution mode (0 or 1)
+  BT_OPT_FLAG_DRY_RUN       Set dry run mode (0 or 1)
+  BT_OPT_FLAG_TREE Set the default subfolder behavior
 EOF
             ;;
         generate)
@@ -332,7 +331,7 @@ Options:
   -o <directory>  Specify the output directory (default: current directory)
 
 Environment variables:
-  BTEST_OUTPUT_DIR    Set the default output directory
+  BT_OPT_OUTPUT_DIR_DEFAULT    Set the default output directory
 EOF
             ;;
         status)
@@ -346,8 +345,8 @@ Options:
   -l, --loglevel  Set the log level
 
 Environment variables:
-  BTEST_VERBOSE       Set verbose mode (0 or 1)
-  BTEST_LOG_LEVEL     Set the default log level
+  BT_OPT_VERBOSE       Set verbose mode (0 or 1)
+  BT_OPT_LOG_LEVEL     Set the default log level
 EOF
             ;;
         *)
@@ -356,7 +355,17 @@ EOF
     esac
 }
 
+
+
+
+
 # Main command processing
+
+BT_DECLARE_PRE="      " bt_init VERBOSE REPORTER OUTPUT_DIR EPOCH_DELTA_MIN ABORT DIR_DEFAULT DEBUG LOG_LEVEL FLAG_DRY_RUN FLAG_TREE
+
+BT_DECLARE_PRE="export" bt_init EPOCH_DELTA_MIN PROTOCOL
+
+
 case $1 in
     version)
         shift
@@ -389,7 +398,12 @@ case $1 in
         display_help
         ;;
     *)
-        echo "Error: Unknown command '$1'" >&2
+        if [[ "$2" ]]; then
+
+            echo "Error: Unknown btest subcommand '$1'" >&2
+
+        fi
+
         display_help
         exit 1
         ;;
